### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by coolpalani** [pusher/k8s-spot-termination-handler#4]
This kubernetes sport termination handler is continuously monitoring and drain the node.
During the gracefully drain the nodes mean what will happen behind the scene. will it move the workload to some other node or make a backup before a node goes away.

What's the real use case of this termination handler. Could you bit describe this.
is there any pre recorded video, It would be great.

**Comment by gargath** [comment]
AWS spot instances are liable to being shut down when the spot price changes or spot instance capacity in a region decreases.

This handler is meant to pick up notification of an impending shutdown and gracefully drain the node of workload before the EC2 instance itself terminates.

It will evict pods from the terminating node, allowing them to be re-scheduled on other nodes.

This makes running kubernetes nodes on EC2 spot instances more reliable and self-managing.

Does this answer your question?

**Comment by coolpalani** [comment]
Thank you for your insight.
I don't think running critical Kubernetes stuffs in spot instance, reliable or not.
Depending on use case and requirement, It still makes sense.
